# Generated by Django 6.0.2 on 2026-02-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_data',
            name='class_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
